### PR TITLE
Shifted few lines and fixed few typos in README.md

### PR DESCRIPTION
**Pull request by LunarMarathon**
Shifted the installation of dependencies lines before the script execution instructions.

### CODE REVIEW

**Review by nightmare-tech — APPROVED** [review]
Improved the README.md :+1:

**Review by nightmare-tech — CHANGES_REQUESTED** [review]
Update your local repo. The pip install instrictions are missing from a recent PR.

**Comment by LunarMarathon** [comment]
I've moved them under "How to run" section since you mentioned that they have to be run before running the script. If it's below, people might miss it and run the script first. 

I'll add the alternative line that another contributor had added and send, is that okay?

**Comment by LunarMarathon** [comment]
image

**Comment by nightmare-tech** [comment]
yes

**Review by nightmare-tech — APPROVED** [review]
:+1:

**Pull request closed without merging**
