### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by spykelionel**
Fix typo

### CODE REVIEW

**Comment by nightmare-tech** [comment]
I have to label this right?

**Comment by spykelionel** [comment]
Yes. hactoberfest-accepted

**Comment by spykelionel** [comment]
Please review and merge. So I can update my branch. Also, drop any comments if necessary thanks

**Comment by nightmare-tech** [comment]
Nice, now my README will be more accurate. Thanks :)

**Review by nightmare-tech — COMMENTED** [review]
They removed a spelling mistake. All cool :+1:

**Pull request merged**
