### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mohakgupt**
ref. #16 

Added a CONTRIBUTING.md file

### CODE REVIEW

**Comment by mohakgupt** [comment]
PS: add the hactoberfest tag

**Review by nightmare-tech — CHANGES_REQUESTED** [review]
The issues hyperlink points to a different repo.

**Comment by mohakgupt** [comment]
> The issues hyperlink points to a different repo.

Corrected

**Comment by nightmare-tech** [comment]
Forgot to write an approving review. Will that be a problem?

**Review by nightmare-tech — APPROVED** [review]
Gtg

**Comment by mohakgupt** [comment]
Its fine

**Pull request merged**
