### PR TITLE
remove key storage

### PR DESCRIPTION
**Pull request by theCasm**
it's a little dirty but should work just fine

### CODE REVIEW

**Comment by nightmare-tech** [comment]
could you explain me what you have done? maybe in discord vc?

**Review by nightmare-tech — COMMENTED** [review]
I cloned your fork in a seperate directory with a fresh python venv. After running the script and storing a sample record, the `filekey.key` is still being produced as you may be able to see in the follwing terminal command:
```

(temp) ┌[user@fedora] [/dev/pts/0] [main] 
└[~/temp/PWD_Vault/PWD_Vault]> ls                     
banners.py  endecrypt.py  help.txt    m_pwd.dat     __pycache__
data.csv    filekey.key   maincsv.py  PWD_Vault.py

```

**Comment by nightmare-tech** [comment]
You also need to change the `PWD_Vault.py` file as there is a try-except block there that forces user to run the first time setup that makes the `filekey.key` file

**Comment by theCasm** [comment]
That's strange... It doesn't do that on my end. The try should only be failing when it tries to read the m_pwd file. `grep -rn . -e 'filekey'` returns no matches, so I have no clue where it would be doing that. I'll clean up the code a bit anyway, maybe see if that works any better when its done

**Comment by nightmare-tech** [comment]
Just so we are on the same page, I clone your forked repo from https://github.com/theCasm/PWD_Vault then I do the following:
```
(temp) ┌[arpit@fedora] [/dev/pts/0] [main] 
└[~/temp/PWD_Vault/PWD_Vault]> ls
banners.py  endecrypt.py  help.txt  maincsv.py  PWD_Vault.py  __pycache__
(temp) ┌[arpit@fedora] [/dev/pts/0] [main] 
└[~/temp/PWD_Vault/PWD_Vault]> python PWD_Vault.py

    
    
   ▄███████▄  ▄█     █▄  ████████▄   ▄█    █▄     ▄████████ ███    █▄   ▄█           ███     
  ███    ███ ███     ███ ███   ▀███ ███    ███   ███    ███ ███    ███ ███       ▀█████████▄ 
  ███    ███ ███     ███ ███    ███ ███    ███   ███    ███ ███    ███ ███          ▀███▀▀██ 
  ███    ███ ███     ███ ███    ███ ███    ███   ███    ███ ███    ███ ███           ███   ▀ 
▀█████████▀  ███     ███ ███    ███ ███    ███ ▀███████████ ███    ███ ███           ███     
  ███        ███     ███ ███    ███ ███    ███   ███    ███ ███    ███ ███           ███     
  ███        ███ ▄█▄ ███ ███   ▄███ ███    ███   ███    ███ ███    ███ ███▌    ▄     ███     
 ▄████▀       ▀███▀███▀  ████████▀   ▀██████▀    ███    █▀  ████████▀  █████▄▄██    ▄████▀   
                                                                       ▀                     

    
    
|-------------------------------------------------------|
|--------------------LOGIN SCREEN ----------------------|
|-------------------------------------------------------|
|----1. Enter the Master Password ----------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|--s = First-Time-Setup (Only run this once) -----------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|----h = Help ------------------------------------------|
|----q = quit ------------------------------------------|
|-------------------------------------------------------|


> s


Enter NEW Master Password
> 0000
Sucessfully encoded new Master Password!


Succesfully generated key!


Great! Now remeber the master passwrd that you encoded as it will not be provided again in future...
'Remember one Strong Password than a 100 weak ones...'
Hit Enter to go to the main menu...> 
|-------------------------------------------------------|
|-------------------------------------------------------|
|-----------------------MAIN MENU ----------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|-----1. Enter in Record -------------------------------|
|-----2. Read all the stored data ----------------------|
|-----3. Search within all the stored data -------------|
|-----4. Delete a record -------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|h = Help ----------------------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|e = erase the file ------------------------------------|
|q = quit ----------------------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
> 1


Enter the name of ````website/ service provider```:
> Sample_service
Enter the ```username/ email-id``` by which the password is stored:
> user@mail.com
Suggest Password?(y/n) >y
Password Generated successfully!!
 Cx>2AXy>NOy0
Copied to Clipboard!!
Recorded Successfully!
Do you want to add another pwd?(y/n)
INVALID OPTION!


Hit Enter to return to the main menu
> 
|-------------------------------------------------------|
|-------------------------------------------------------|
|-----------------------MAIN MENU ----------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|-----1. Enter in Record -------------------------------|
|-----2. Read all the stored data ----------------------|
|-----3. Search within all the stored data -------------|
|-----4. Delete a record -------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|h = Help ----------------------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
|e = erase the file ------------------------------------|
|q = quit ----------------------------------------------|
|-------------------------------------------------------|
|-------------------------------------------------------|
> q
Encrypting Data...
Exiting...
(temp) ┌[arpit@fedora] [/dev/pts/0] [main] 
└[~/temp/PWD_Vault/PWD_Vault]> ls                                            
banners.py  endecrypt.py  help.txt    m_pwd.dat     __pycache__
data.csv    filekey.key   maincsv.py  PWD_Vault.py



```

**Comment by theCasm** [comment]
I think you cloned the wrong branch

**Comment by nightmare-tech** [comment]
Sorry, I cloned the main branch

**Comment by nightmare-tech** [comment]
I'll try it after some time (1-2) hrs.

**Comment by nightmare-tech** [comment]
I'll try it after some time (1-2) hrs.

**Comment by nightmare-tech** [comment]
Woah, it works! I have to research on what you have done... But its great !! Thanks. I have been genuinely looking for solutions to this for so long :heart:

**Comment by nightmare-tech** [comment]
Someone suggested me that the salt should not be static...

**Comment by theCasm** [comment]
A static salt will work. A better method is to use a random salt and store it. I'm going to improve my fix rq, I made it pretty late and now I'm starting to see a lot of issues with it

**Pull request closed without merging**
