### PR TITLE
create requirements txt file.

### LINKED ISSUE #5: Add requirements.txt file
For easy package installation

### PR DESCRIPTION
**Pull request by spykelionel**
: For easy installation
: closes #5

### CODE REVIEW

**Comment by nightmare-tech** [comment]
what if the versions change?

**Comment by nightmare-tech** [comment]
But ig its good for stability.

**Review by nightmare-tech — CHANGES_REQUESTED** [review]
remove `cryptography` and `getpass` they are inbuilt now.

**Comment by spykelionel** [comment]
> what if the versions change?

Then the `requirements.txt` file will be updated accordingly I guess

**Review by nightmare-tech — APPROVED** [review]
Removed built-ins. Good to merge :+1:

**Comment by spykelionel** [comment]
hacktoberfest-accepted label not added

**Comment by nightmare-tech** [comment]
sorry

**Pull request merged**
