### PR TITLE
Formatted Readme and Added missing package in requirements.txt

### LINKED ISSUE #11: Create a Table of Contents for the README.md
It should only have the heading with `#` tag.

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/nightmare-tech/PWD_Vault/issues/11
- Added Table of Contents to Readme
- Changed some words in the text
- Removed pip install getpass as it is a standard module and pip install getpass wont work
- Added missing package (cryptography) to requirements.txt

### CODE REVIEW

**Review by nightmare-tech — CHANGES_REQUESTED** [review]
Remove `cryptography` form the txt and README.
Its included in standard too...

**Review by nightmare-tech — APPROVED** [review]
Sorry, it was my misunderstanding. Hope you don't mind.

**Comment by nightmare-tech** [comment]
commit it again. I will merge

**Comment by Ananthavijay** [comment]
No problem, should I add cryptography again?

**Comment by nightmare-tech** [comment]
yes

**Comment by Ananthavijay** [comment]
Done! Thanks

**Review by nightmare-tech — APPROVED** [review]
GTG! :+1:

**Pull request merged**
