### PR TITLE
Add LICENSE file to PWD_Vault Repo

### PR DESCRIPTION
**Pull request by fernandoleira**
Hello! I noticed the repo was missing the LICENSE file, so this PR creates an Apache License for PWD_Vault under the project owner's name.

### CODE REVIEW

**Comment by nightmare-tech** [comment]
How is this useful?

**Comment by fernandoleira** [comment]
Open source licenses are very recommended for software systems/projects for them to be available and usable by others, even if it has been publicly posted on GitHub. Each open source license states what users are permitted to do with the code on the repo and their obligations or what they cannot do as listed in the terms and conditions.

Opensource.guide has a very good article on why it's important for open-source projects to have their licensing defined. For more info here is their post: [https://opensource.guide/legal/](https://opensource.guide/legal/).

**Comment by nightmare-tech** [comment]
Why didn't you choose the MIT license?

**Comment by fernandoleira** [comment]
Wasn't sure the required licensing purpose needed for this repo, so I'm using Apache since it's a very good one for general open source projects.

I can go ahead and change it for MIT if you need to.

**Comment by nightmare-tech** [comment]
yes change it to MIT thanks

**Comment by nightmare-tech** [comment]
sorry, I did it myself

**Pull request closed without merging**
